import re

el_list = ['Name:',
 'Company:',
 'LAW OFFICES OF ALAN ABERGEL, P.C.',
 'Offers Consumer Loans:',
 ' No ',
 'Offers Out of State Loans:',
 ' No ',
 'Minimum Loan Amount:',
 '$0.00',
 'Maximum Loan Amount:',
 '$0.00',
 'Address:',
 '15915 Ventura Blvd., Suite 300',
 'Encino, CA 91436',
 'Phone:',
 '(818) 783-4645',
 'Fax:',
 'Email:',
 'Website:',
 'Name:',
 'Company:',
 'PD Financial Group',
 'Offers Consumer Loans:',
 ' No ',
 'Offers Out of State Loans:',
 ' No ',
 'Minimum Loan Amount:',
 '$0.00',
 'Maximum Loan Amount:',
 '$0.00',
 'Address:',
 '2255 Lemon Avenue',
 'Long Beach, CA 90806',
 'Phone:',
 '(800) 580-4913',
 'Fax:',
 '(800) 580-4916',
 'Email:',
 'Website:',
 'Name:',
 'Company:',
 'FCI Lender Services, Inc.',
 'Offers Consumer Loans:',
 ' No ',
 'Offers Out of State Loans:',
 ' No ',
 'Minimum Loan Amount:',
 '$0.00',
 'Maximum Loan Amount:',
 '$0.00',
 'Address:',
 '8180 E Kaiser Blvd.',
 'Anaheim Hills, CA 92808',
 'Phone:',
 '(800) 931-2424',
 'Fax:',
 '(714) 282-2425',
 'Email:',
 'Website:',
 'Name:',
 'Company:',
 'Halcyon Capital Solutions',
 'Offers Consumer Loans:',
 ' No ',
 'Offers Out of State Loans:',
 ' No ',
 'Minimum Loan Amount:',
 '$0.00',
 'Maximum Loan Amount:',
 '$0.00',
 'Address:',
 '3727 West Magnolia Blvd #727',
 'Burbank, CA 91505',
 'Phone:',
 '(818) 402-2101',
 'Fax:',
 '(818) 239-5136',
 'Email:',
 'Website:',
 'Name:',
 'Company:',
 'Available Home Loans, Inc.',
 'Offers Consumer Loans:',
 ' No ',
 'Offers Out of State Loans:',
 ' No ',
 'Minimum Loan Amount:',
 '$0.00',
 'Maximum Loan Amount:',
 '$0.00',
 'Address:',
 '688 N. Arrowhead Avenue, Suite 204',
 'San Bernardino, CA 92401',
 'Phone:',
 '(909) 383-0813',
 'Fax:',
 '(909) 888-0923',
 'Email:',
 'Website:',
 'Name:',
 'Company:',
 'DFI Funding, Inc.',
 'Offers Consumer Loans:',
 ' No ',
 'Offers Out of State Loans:',
 ' No ',
 'Minimum Loan Amount:',
 '$50,000.00',
 'Maximum Loan Amount:',
 '$6,000,000.00',
 'Address:',
 '78-365 Highway 111 #529',
 'La Quinta, CA 92253',
 'Phone:',
 '(510) 420-8698',
 'Fax:',
 '(760) 406-5065',
 'Email:',
 'Website:',
 'Name:',
 'Company:',
 'BDM Mortgage Services',
 'Offers Consumer Loans:',
 ' No ',
 'Offers Out of State Loans:',
 ' No ',
 'Minimum Loan Amount:',
 '$50,000.00',
 'Maximum Loan Amount:',
 '$1,000,000.00',
 'Address:',
 '21601 Devonshire Street, #219',
 'Chatsworth, CA 91311',
 'Phone:',
 '(818) 708-8889',
 'Fax:',
 '(818) 708-1926',
 'Email:',
 'Website:',
 'Name:',
 'Company:',
 'Unitrust Mortgage, Inc.',
 'Offers Consumer Loans:',
 ' No ',
 'Offers Out of State Loans:',
 ' No ',
 'Minimum Loan Amount:',
 '$0.00',
 'Maximum Loan Amount:',
 '$0.00',
 'Address:',
 'P.O. Box 1502030',
 'San Diego, CA 92195',
 'Phone:',
 '(619) 540-5788',
 'Fax:',
 '(858) 404-7323',
 'Email:',
 'Website:',
 'Name:',
 'Company:',
 'Olympia Financial Mortgage Inc.',
 'Offers Consumer Loans:',
 ' No ',
 'Offers Out of State Loans:',
 ' No ',
 'Minimum Loan Amount:',
 '$0.00',
 'Maximum Loan Amount:',
 '$0.00',
 'Address:',
 '16633 Ventura Blvd., Suite 1050',
 'Encino, CA 91436',
 'Phone:',
 '(818) 885-8585',
 'Fax:',
 '(818) 788-8471',
 'Email:',
 'Website:',
 'Name:',
 'Company:',
 'Woodland Hills Mortgage Corp',
 'Offers Consumer Loans:',
 ' No ',
 'Offers Out of State Loans:',
 ' No ',
 'Minimum Loan Amount:',
 '$0.00',
 'Maximum Loan Amount:',
 '$0.00',
 'Address:',
 '21777 Ventura Blvd., Suite 211',
 'Woodland Hills, CA 91364',
 'Phone:',
 'Fax:',
 'Email:',
 'Website:',
 'Name:',
 'Company:',
 'Valley Mortgage Investments, Inc.',
 'Offers Consumer Loans:',
 ' No ',
 'Offers Out of State Loans:',
 ' No ',
 'Minimum Loan Amount:',
 '$0.00',
 'Maximum Loan Amount:',
 '$0.00',
 'Address:',
 '5100 California Avenue, Suite 122',
 'Bakersfield, CA 93309',
 'Phone:',
 '(661) 633-1600',
 'Fax:',
 '(661) 616-1100',
 'Email:',
 'Website:',
 'Name:',
 'Company:',
 'Crawford Real Estate Services, Inc.',
 'Offers Consumer Loans:',
 ' No ',
 'Offers Out of State Loans:',
 ' No ',
 'Minimum Loan Amount:',
 '$10,000.00',
 'Maximum Loan Amount:',
 '$5,000,000.00',
 'Address:',
 '1770 North  Arrowhead Avenue',
 'San Bernardino, CA 92406',
 'Phone:',
 '(909) 882-3393',
 'Fax:',
 '(909) 882-3230',
 'Email:',
 'Website:',
 'Name:',
 'Company:',
 'Triumph Capital Partners, LLC',
 'Offers Consumer Loans:',
 ' No ',
 'Offers Out of State Loans:',
 ' No ',
 'Minimum Loan Amount:',
 '$0.00',
 'Maximum Loan Amount:',
 '$0.00',
 'Address:',
 '662 Encinitas Blvd., Suite 208',
 'Encinitas, CA 92024',
 'Phone:',
 '(858) 490-2180',
 'Fax:',
 'Email:',
 'Website:',
 'Name:',
 'Company:',
 'Unitrust Mortgage, Inc.',
 'Offers Consumer Loans:',
 ' No ',
 'Offers Out of State Loans:',
 ' No ',
 'Minimum Loan Amount:',
 '$0.00',
 'Maximum Loan Amount:',
 '$0.00',
 'Address:',
 'P.O. Box 1502030',
 'San Diego, CA 92195',
 'Phone:',
 '(619) 540-5788',
 'Fax:',
 '(858) 404-7323',
 'Email:',
 'Website:',
 'Name:',
 'Company:',
 'Diamond Potrans',
 'Offers Consumer Loans:',
 ' No ',
 'Offers Out of State Loans:',
 ' No ',
 'Minimum Loan Amount:',
 '$0.00',
 'Maximum Loan Amount:',
 '$0.00',
 'Address:',
 '20955 Pathfinder Road Suite 338',
 'Diamond Bar, CA 91765',
 'Phone:',
 '(909) 598-1405',
 'Fax:',
 'Email:',
 'Website:',
 'Name:',
 'Company:',
 'Ross Diversified Insurance Services, Inc.',
 'Offers Consumer Loans:',
 ' No ',
 'Offers Out of State Loans:',
 ' No ',
 'Minimum Loan Amount:',
 '$0.00',
 'Maximum Loan Amount:',
 '$0.00',
 'Address:',
 '2922 East Chapman Ave. Suite 203',
 'Orange, CA 92869',
 'Phone:',
 '(714) 633-7677',
 'Fax:',
 '(714) 633-7788',
 'Email:',
 'Website:',
 'Name:',
 'Company:',
 'JB Private Investments',
 'Offers Consumer Loans:',
 ' No ',
 'Offers Out of State Loans:',
 ' No ',
 'Minimum Loan Amount:',
 '$50,000.00',
 'Maximum Loan Amount:',
 '$20,000,000.00',
 'Address:',
 '651 Fordham Road',
 'San Mateo, CA 94402',
 'Phone:',
 '(650) 315-9933',
 'Fax:',
 '(650) 332-2318',
 'Email:',
 'Website:',
 'Name:',
 'Company:',
 'FJM Capital, Inc.',
 'Offers Consumer Loans:',
 ' No ',
 'Offers Out of State Loans:',
 ' No ',
 'Minimum Loan Amount:',
 '$0.00',
 'Maximum Loan Amount:',
 '$0.00',
 'Address:',
 '1372 North McDowell Blvd., Suite D',
 'Petaluma, CA 94954',
 'Phone:',
 '(415) 479-9612',
 'Fax:',
 'Email:',
 'Website:',
 'Name:',
 'Company:',
 'James Baron',
 'Offers Consumer Loans:',
 ' No ',
 'Offers Out of State Loans:',
 ' No ',
 'Minimum Loan Amount:',
 '$0.00',
 'Maximum Loan Amount:',
 '$0.00',
 'Address:',
 '19830 Via Escuela Drive',
 'Saratoga, CA 95070',
 'Phone:',
 '(408) 206-6050',
 'Fax:',
 'Email:',
 'Website:',
 'Name:',
 'Company:',
 'Black Square Real Estate',
 'Offers Consumer Loans:',
 ' No ',
 'Offers Out of State Loans:',
 ' No ',
 'Minimum Loan Amount:',
 '$0.00',
 'Maximum Loan Amount:',
 '$0.00',
 'Address:',
 'P.O. Box 3390',
 'Salt Lake City, UT 84110',
 'Phone:',
 '(801) 243-8700',
 'Fax:',
 'Email:',
 'Website:']
e = dict()
fieldregex = re.compile(r'.+:$')
cityregex = re.compile(r"^.+(?= )")
stateregex = re.compile(r"[A-Z]{2}")
zipregex = re.compile(r"\d{5}$")



for number, line in enumerate(el_list):
    if line == 'Name:' and number != 0:
        print(e)
        e.clear()
        e[line] = ''
        continue
    elif fieldregex.findall(line):
        e[line] = ''
    elif fieldregex.findall(el_list[number-1]):
        e[el_list[number-1]] = line
    else:
        try:
            e['City'] = cityregex.findall(line)[0]
            e['State'] = stateregex.findall(line)[0]
            e['PostalCode'] = zipregex.findall(line)[0]
        except IndexError:
            pass


